### ISSUE TITLE
problem getting pager settings

### ISSUE THREAD

**Issue by gehbeez** [brantwills/Angular-Paging#14]
i want to make this
    <div paging class="small"
                 page="1"
                 page-size="20"
                 total="100"
                 adjacent="2"
                 dots="...."
                 scroll-top="true"
                 hide-if-empty="true"
                 ul-class="pagination"
                 disabled-class="disabled"
                 show-prev-next="true"
                 paging-action="DoCtrlPagingAct('Paging Clicked',page,pageSize, total)">
            </div>
and pass pager parameters to my function 
pageSize and total always undefined

**Comment by brantwills** [comment]
Hey Gehbeez,

By design only the `page` attribute is being exposed by the `internalAction` method in the directive which is why `pageSize` and `total` are undefined.

I do no see any harm exposing the pageSize and total attributes which would solve your issue. 
In short, adding them to the pagingAction like so:

```javascript
function internalAction(scope, page) {
   ...
        scope.pagingAction({
            page: page,
          +  pageSize: scope.pageSize,
          +  total: scope.total
        });
   ...
}
```
I would like to take some time and test these additions
I want to make sure we don't throw off the pageSize or total values say in a controller scope.  

In theory there should be no conflict and I'll get this in there as soon as possible
Thank you so much for bringing this up!
