### ISSUE TITLE
Breaks scope

### ISSUE THREAD

**Issue by lewiswharf** [brantwills/Angular-Paging#29]
I'm attempting to use the angular-paging directive inside a nested `ui-view`. 

    <div ui-view="messages" flex>
        <md-list role="list">
            <md-list-item ng-repeat="message in messages" class="md-3-line">
            ...
            </md-list-item>
        </md-list>
        <paging
                page="messages.meta.pagination.current_page"
                page-size="messages.meta.pagination.per_page"
                total="messages.meta.pagination.total"
                show-prev-next="true"
                paging-action="paginate(page)">
        </paging>
    </div>

If I move the angular-paging directive outside the `div` the directive works as usual. It appears to break the scope but I cannot figure out exactly what is happening or how to fix it.

**Comment by brantwills** [comment]
Hey lewiswharf, 

In just glancing at the code, could you elaborate on what the `messages` object is at each stage of your example code?

I am alittle confused as to why messages is the ui-view name (thinking you are using ui-router?), and data source for the repeater in `md-list` (thinking you are using angular material?), and yet it also contains a `meta` child object for the paging directive.  

I could be totally wrong, but I get the sense outside the ui-view div our `messages` object may be a different in that it contains the meta child object which is why the directive may successfully outside. However once we enter the ui-view, we have set messages maybe to an array? which we iterate over in the ng-repeat and lose the meta information?

It may be helpful to run the following and see what happens - let me know if there are any questions - apologies I wrote this up pretty quick at the end of the day!

```html
<div ui-view="messages" flex>
    <md-list role="list">
        <md-list-item ng-repeat="message in messages" class="md-3-line">
        ...
        </md-list-item>
    </md-list>
     
    <h4> Does Anything Appear Below? </h4>
    <div ng-bind="messages.meta.pagination.current_page"></div>
    <div ng-bind="messages.meta.pagination.per_page"></div>
    <div ng-bind="messages.meta.pagination.total"></div>

    <h4> Bonus, what is messages at this point? </h4>
    {{messages}}
</div>

<hr/>

<h4>Outside the DIV we know things work right? </h4>
<div ng-bind="messages.meta.pagination.current_page"></div>
<div ng-bind="messages.meta.pagination.per_page"></div>
<div ng-bind="messages.meta.pagination.total"></div>
```

**Comment by lewiswharf** [comment]
Thanks for the quick reply @brantwills.

messages (as in... ng-repeat="message in messages") represents a [restangular](https://github.com/mgonto/restangular) collection. Meta prints inside and outside the `div` correctly (same). `{{ messages }} prints the same inside and out as well. I also tried moving the pagination meta in the controller to `$scope.pagination` with no change.

I'll try to reproduce in a fiddle tomorrow.

**Comment by lewiswharf** [comment]
I'm now fairly confident this is a bug related to ui-router. I've been able to circumnavigate the problem by eliminating the nested `ui-view` design I had implemented.

**Comment by brantwills** [comment]
Aw that is kinda a bummer but happy to hear you were able to find a workaround!
Thanks for the update and checking out the directive
