### ISSUE TITLE
Custom HTML for next/previous text

### ISSUE THREAD

**Issue by ztoliver** [brantwills/Angular-Paging#41]
I'm pretty new to angular, but I was wondering if it was possible with this great project to add custom HTML instead of a string to the previous/next text in paging.js instead of just "<,>". I'm attempting to combine this paging implementation with MaterialzeCSS and the styling is off with the current previous/next characters.

I've tried using jquery to replace the innerHtml of those elements but they always load after document ready so the innerHtml injection/replacement isn't happening. It works fine via the console after all of the elements on the page are loaded.

Example: (Note I'm not using Bootstrap, rather MaterializeCSS)
What I need instead of "<" is :

&lsaquo;i class="material-icons"&rsaquo;chevron_left&lsaquo;/i&rsaquo;

jQuery code to replace ">":

$(".pagination li[title='Previous Page'] a").html('&lsaquo;i class="material-icons"&rsaquo;chevron_left&lsaquo;/i&rsaquo;');

Thanks

**Comment by brantwills** [comment]
Hey ztoliver,

My apologies for the delay in response!  To directly answer your question at this time it is not possible to inject HTML into the previous/next text without forking the paging.js file.

However, you bring up an excellent point that something like this should be supported.  In my initial research I feel instead of dropping HTML into the text perhaps it would be helpful to provide a custom class attribute for previous/next icons.  

This would allow anyone to drop a custom css icon class value and text if needed like in materializeCSS in place of the "<,>" characters.

---

In the meantime if you are still having issues with your jQuery, I'll try to work up a plunker to replicate the error and maybe provide some help.  Thanks again for logging the issue!

**Comment by brantwills** [comment]
Alrighty, got some working code published to iss41 branch 

I need to write up the tests but once complete will merge to master!

**Comment by brantwills** [comment]
Closed with version 2.2.0 release

**Comment by ztoliver** [comment]
brantwills,

Thank you for your hard work and dedication on the Angular-Paging project. The addition of first, last, next, and prev class objects will make it much easier to integrate this awesome work with many styles.

In the case of MaterializeCss, which makes use of Google's Material Icons, a custom class "material-icons" is passed to an element, but the icons are rendered inside of the given element using text content such as "thumb_down" or "navigate_right". Since I made the decision to use MaterializeCss over something like Bootstrap I will work to find another way, using the enhancements you created, to add stylized navigation icons to my page.

Once again thanks for your swift response, dedication, and hard work.
